using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using TenXConvo.Infrastructure.Data;

namespace TenXConvo.Infrastructure.Migrations;

// ═══════════════════════════════════════════════════════════════════════════
//  EF CORE MODEL SNAPSHOT
//  Auto-used by EF to track current migration state.
//  Do not edit manually — regenerated by: dotnet ef migrations add <Name>
// ═══════════════════════════════════════════════════════════════════════════

[DbContext(typeof(AppDbContext))]
partial class AppDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

        modelBuilder.Entity("TenXConvo.Domain.Entities.AppRole", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<string>("RoleName").IsRequired().HasMaxLength(100);
            b.Property<DateTime>("CreatedOn");
            b.HasKey("Id");
            b.HasIndex("RoleName").IsUnique();
            b.ToTable("Roles");
        });

        modelBuilder.Entity("TenXConvo.Domain.Entities.AppUser", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<string>("UserName").IsRequired().HasMaxLength(200);
            b.Property<string>("LoginId").IsRequired().HasMaxLength(100);
            b.Property<string>("Email").IsRequired().HasMaxLength(200);
            b.Property<string>("PasswordHash").IsRequired();
            b.Property<string>("CellNo").HasMaxLength(20);
            b.Property<string>("ImageUrl").HasMaxLength(500);
            b.Property<Guid?>("RoleId");
            b.Property<bool>("IsActive");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("Email").IsUnique();
            b.HasIndex("LoginId").IsUnique();
            b.HasIndex("RoleId");
            b.ToTable("Users");
        });

        modelBuilder.Entity("TenXConvo.Domain.Entities.FiscalYear", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<string>("Name").IsRequired().HasMaxLength(100);
            b.Property<DateTime>("StartDate");
            b.Property<DateTime>("EndDate");
            b.Property<bool>("IsActive");
            b.Property<bool>("IsCurrent");
            b.Property<DateTime>("CreatedAt");
            b.HasKey("Id");
            b.ToTable("FiscalYears");
        });

        modelBuilder.Entity("TenXConvo.Domain.Entities.ConsultantProfile", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("UserId");
            b.Property<string>("Bio").HasMaxLength(500);
            b.Property<string>("AvatarUrl").HasMaxLength(500);
            b.Property<bool>("IsOnline");
            b.Property<bool>("IsPublic");
            b.Property<DateTime>("JoinedDate");
            b.Property<string>("Specialization").HasMaxLength(300);
            b.Property<string>("Experience").HasMaxLength(300);
            b.Property<decimal?>("HourlyRate");
            b.Property<DateTime?>("UpdatedAt");
            b.HasKey("Id");
            b.HasIndex("UserId").IsUnique();
            b.ToTable("ConsultantProfiles");
        });

        modelBuilder.Entity("TenXConvo.Domain.Entities.Conversation", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("ConsultantId");
            b.Property<Guid>("CustomerId");
            b.Property<DateTime>("CreatedAt");
            b.Property<DateTime?>("LastMessageAt");
            b.Property<bool>("IsActive");
            b.HasKey("Id");
            b.HasIndex("ConsultantId");
            b.HasIndex("CustomerId");
            b.ToTable("Conversations");
        });


        modelBuilder.Entity("TenXConvo.Domain.Entities.PasswordResetToken", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("UserId");
            b.Property<string>("Token").IsRequired().HasMaxLength(10);
            b.Property<DateTime>("ExpiresAt");
            b.Property<bool>("IsUsed");
            b.Property<string>("IpAddress").HasMaxLength(45);
            b.Property<DateTime>("CreatedAt");
            b.HasKey("Id");
            b.HasIndex("Token");
            b.HasIndex("UserId", "IsUsed");
            b.ToTable("PasswordResetTokens");
        });

        modelBuilder.Entity("TenXConvo.Domain.Entities.Message", b =>
        {
            b.Property<Guid>("Id").ValueGeneratedOnAdd();
            b.Property<Guid>("ConversationId");
            b.Property<Guid>("SenderId");
            b.Property<string>("Body").IsRequired();
            b.Property<string>("MessageType").IsRequired().HasMaxLength(20);
            b.Property<string>("AttachmentUrl").HasMaxLength(500);
            b.Property<bool>("IsRead");
            b.Property<DateTime>("SentAt");
            b.Property<DateTime?>("ReadAt");
            b.Property<DateTime?>("DeletedAt");
            b.HasKey("Id");
            b.HasIndex("ConversationId");
            b.HasIndex("SenderId");
            b.ToTable("Messages");
        });
    }
}
